theory Schem_Lift_Defs
  imports Auto_Lifter_Lifters Auto_Lifter_Sets
begin


lemmas schem_lift_defs =
  schem_lift_base_trivA_def
  schem_lift_base_trivB_def
  schem_lift_base_trivC_def
  schem_lift_base_trivD_def
  schem_lift_base_trivE_def
  schem_lift_base_trivF_def
  schem_lift_base_trivG_def
  schem_lift_base_trivH_def
  schem_lift_base_trivI_def
  schem_lift_base_trivJ_def
  schem_lift_base_trivK_def
  schem_lift_base_idA_def
  schem_lift_base_idB_def
  schem_lift_base_idC_def
  schem_lift_base_idD_def
  schem_lift_base_idE_def
  schem_lift_base_idF_def
  schem_lift_base_idG_def
  schem_lift_base_idH_def
  schem_lift_base_idI_def
  schem_lift_base_idJ_def
  schem_lift_base_idK_def
schem_lift_inject_def

schem_lift_option_recR_def

schem_lift_prio_recR_def

schem_lift_recL_def

  schem_lift_prod_recR_A_left_def
  schem_lift_prod_recR_A_right_def
  schem_lift_prod_recR_B_left_def
  schem_lift_prod_recR_B_right_def
  schem_lift_prod_recR_C_left_def
  schem_lift_prod_recR_C_right_def
  schem_lift_prod_recR_D_left_def
  schem_lift_prod_recR_D_right_def
  schem_lift_prod_recR_E_left_def
  schem_lift_prod_recR_E_right_def
  schem_lift_prod_recR_F_left_def
  schem_lift_prod_recR_F_right_def
  schem_lift_prod_recR_G_left_def
  schem_lift_prod_recR_G_right_def
  schem_lift_prod_recR_H_left_def
  schem_lift_prod_recR_H_right_def
  schem_lift_prod_recR_I_left_def
  schem_lift_prod_recR_I_right_def
  schem_lift_prod_recR_J_left_def
  schem_lift_prod_recR_J_right_def
  schem_lift_prod_recR_K_left_def
  schem_lift_prod_recR_K_right_def
  schem_lift_merge_recR_A_left_def
  schem_lift_merge_recR_A_right_def
  schem_lift_merge_recR_B_left_def
  schem_lift_merge_recR_B_right_def
  schem_lift_merge_recR_C_left_def
  schem_lift_merge_recR_C_right_def
  schem_lift_merge_recR_D_left_def
  schem_lift_merge_recR_D_right_def
  schem_lift_merge_recR_E_left_def
  schem_lift_merge_recR_E_right_def
  schem_lift_merge_recR_F_left_def
  schem_lift_merge_recR_F_right_def
  schem_lift_merge_recR_G_left_def
  schem_lift_merge_recR_G_right_def
  schem_lift_merge_recR_H_left_def
  schem_lift_merge_recR_H_right_def
  schem_lift_merge_recR_I_left_def
  schem_lift_merge_recR_I_right_def
  schem_lift_merge_recR_J_left_def
  schem_lift_merge_recR_J_right_def
  schem_lift_merge_recR_K_left_def
  schem_lift_merge_recR_K_right_def

lemmas schem_lift_S_defs =
  schem_lift_S_base_idA_def
  schem_lift_S_base_idB_def
  schem_lift_S_base_idC_def
  schem_lift_S_base_idD_def
  schem_lift_S_base_idE_def
  schem_lift_S_base_idF_def
  schem_lift_S_base_idG_def
  schem_lift_S_base_idH_def
  schem_lift_S_base_idI_def
  schem_lift_S_base_idJ_def
  schem_lift_S_base_idK_def


schem_lift_S_inject_def

schem_lift_S_option_recR_def

schem_lift_S_prio_recR_def

schem_lift_S_recL_def

  schem_lift_S_prod_recR_A_left_def
  schem_lift_S_prod_recR_A_right_def
  schem_lift_S_prod_recR_B_left_def
  schem_lift_S_prod_recR_B_right_def
  schem_lift_S_prod_recR_C_left_def
  schem_lift_S_prod_recR_C_right_def
  schem_lift_S_prod_recR_D_left_def
  schem_lift_S_prod_recR_D_right_def
  schem_lift_S_prod_recR_E_left_def
  schem_lift_S_prod_recR_E_right_def
  schem_lift_S_prod_recR_F_left_def
  schem_lift_S_prod_recR_F_right_def
  schem_lift_S_prod_recR_G_left_def
  schem_lift_S_prod_recR_G_right_def
  schem_lift_S_prod_recR_H_left_def
  schem_lift_S_prod_recR_H_right_def
  schem_lift_S_prod_recR_I_left_def
  schem_lift_S_prod_recR_I_right_def
  schem_lift_S_prod_recR_J_left_def
  schem_lift_S_prod_recR_J_right_def
  schem_lift_S_prod_recR_K_left_def
  schem_lift_S_prod_recR_K_right_def
  schem_lift_S_merge_recR_A_left_def
  schem_lift_S_merge_recR_A_right_def
  schem_lift_S_merge_recR_B_left_def
  schem_lift_S_merge_recR_B_right_def
  schem_lift_S_merge_recR_C_left_def
  schem_lift_S_merge_recR_C_right_def
  schem_lift_S_merge_recR_D_left_def
  schem_lift_S_merge_recR_D_right_def
  schem_lift_S_merge_recR_E_left_def
  schem_lift_S_merge_recR_E_right_def
  schem_lift_S_merge_recR_F_left_def
  schem_lift_S_merge_recR_F_right_def
  schem_lift_S_merge_recR_G_left_def
  schem_lift_S_merge_recR_G_right_def
  schem_lift_S_merge_recR_H_left_def
  schem_lift_S_merge_recR_H_right_def
  schem_lift_S_merge_recR_I_left_def
  schem_lift_S_merge_recR_I_right_def
  schem_lift_S_merge_recR_J_left_def
  schem_lift_S_merge_recR_J_right_def
  schem_lift_S_merge_recR_K_left_def
  schem_lift_S_merge_recR_K_right_def


end
